### ISSUE TITLE
Inspector output 7ca6639fef7aa0b32267c0d5490b550729ed998a

### ISSUE THREAD

**Issue by Misaka-0x447f** [projectEverythingMonitor/nicehashStatus#1]
## 工程配置与代码风格
- [x] 	不使用vue-cli，从零开始手写所有webpack配置，需要配置的内容包括但不限于: babel, eslint.
	手动安装所有依赖，所有使用到的依赖都需要知晓其用途，没有用到的依赖不应保留。
        *用意并非背诵
        [documention](http://vuejs-templates.github.io/webpack/)
        找不到未使用的依赖。自动清理插件错误地清理了正在使用的npm package.
        possible duplicate package: superagent + superagent-throttle
        已完成训练：Webpack 等级I
        https://github.com/Misaka-0x447f/otomads
        https://github.com/Misaka-0x447f/playground/blob/master/js/webpack/webpack.config.js
----
- [x]  #5 所有异步逻辑使用async await，请勿滥用callback。
	并调研在2018年，使用async await并兼容部分旧浏览器有哪些方案，各自的原理及优缺点是什么？
	最后采用何种方案，说明原因。
----
- [ ]  尝试使用cssModules改写less代码，并总结两者的优缺点。
----
## 性能分析与改良
- [x]  #2 使用F12: Performance工具对该应用程序进行首次加载性能分析，并总结性能开销情况。
----
- [x]  #3 尝试使用functional components替代部分组件。可以使用模板也可以使用jsx。
	问题1：哪些组件可以改写成functional的？哪些不能？
	问题2：何种情况下functional组件会导致更差的性能？
----
- [x]  阅读 ["Avoid Large, Complex Layouts and Layout Thrashing"](https://developers.google.com/web/fundamentals/performance/rendering/avoid-large-complex-layouts-and-layout-thrashing )
	指出[这段代码](https://github.com/projectEverythingMonitor/nicehashStatus/blob/7ca6639fef7aa0b32267c0d5490b550729ed998a/src/components/GeneralInfo/Panel.vue#L192-L207)违反了哪一条规则，并做出相应修改。
        [翻译](https://gist.github.com/Misaka-0x447f/4773d604b23f964a1b5e47fbd9db0835)
        违反规则：[缺少缓存](https://gist.github.com/Misaka-0x447f/4773d604b23f964a1b5e47fbd9db0835#避免强制同步布局)。对panelSize执行修改将导致大量布局更新，应先读后写。
        改进比较：
before![before](https://user-images.githubusercontent.com/15797507/38192654-80c44df2-36a0-11e8-90d8-114208921552.png)
after
![after](https://user-images.githubusercontent.com/15797507/38192695-b1b4d742-36a0-11e8-830b-915dfc536b94.png)
![image](https://user-images.githubusercontent.com/15797507/38192714-d26180d0-36a0-11e8-8086-dd2b4774423e.png)
----

- [x] #10 将[这段代码](https://github.com/projectEverythingMonitor/nicehashStatus/blob/7ca6639fef7aa0b32267c0d5490b550729ed998a/src/components/PopUpInput.vue#L45-L49)的相关代码改写成事件代理的模式（只允许使用v-on:click="buttonClick",而不允许v-on:click="buttonClick(…)"的模式)
	问题1：使用v-on:click="buttonClick(i)"时，绑定给span的listener是什么？
	问题2：使用v-on:click="buttonClick"时，绑定给span的listener是什么？用这种方式(事件代理)有什么好处？
----
## 用户界面
- [x]  完成loading spinner
- [x]  完成transition
----
## Javascript基础
- [x]  关于[这段代码](https://github.com/projectEverythingMonitor/nicehashStatus/blob/7ca6639fef7aa0b32267c0d5490b550729ed998a/src/components/GeneralInfo/Panel.vue#L221-L222)
	不允许通过参数传入this，也不允许使用[.call](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Function/call)/.apply，应该怎么写？
[The bind method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this#The_bind_method), Arrow functions...  
----
- [x]  runAsyncQuery函数太长。将不必要放在函数体内内容移出，放入子模块中。
----
- [x]  #9 解释[这段代码](https://github.com/projectEverythingMonitor/nicehashStatus/blob/7ca6639fef7aa0b32267c0d5490b550729ed998a/src/components/GeneralInfo/Panel.vue#L155)为什么会导致内存泄漏，并进行修复
----
- [x]  #9 解释[这段代码](https://github.com/projectEverythingMonitor/nicehashStatus/blob/7ca6639fef7aa0b32267c0d5490b550729ed998a/src/components/PopUpInput.vue#L208-L210)为什么不会导致内存泄漏，以及为什么会造成性能浪费？
----
- [x]  #7 使用ES6的模板字符串改写所有的stringifyValue和用到[].join()来构建字符串的地方
	并做实验：模板字符串和[].join()哪一种性能更好？性能差的那个差在哪里？
----
- [x]  公用工具函数放进util.js，不允许出现随手乱写的函数，如isNumeric
----
[requirements.txt](https://github.com/projectEverythingMonitor/nicehashStatus/files/1870558/requirements.txt)
